### ISSUE TITLE
@monorepo-utilities/install-dependencies^0.1.1 was published without any `dist/*.js`

### ISSUE THREAD

**Issue by randytarampi** [monorepo-utilities/monorepo-utilities#36]
## Requested Update

Hey @yowainwright, this works great, except I had to publish my own [@randy.tarampi/install-dependencies@0.1.6](https://www.npmjs.com/package/@randy.tarampi/install-dependencies) 'cause there are no `dist/*.js` files in https://registry.npmjs.org/@monorepo-utilities/install-dependencies/-/install-dependencies-0.1.6.tgz

## Why Is This Update Needed?

'cause I'd like to use the intended published changes.

## Are There Examples Of This Requested Update Elsewhere?

Nope.

**Comment by yowainwright** [comment]
@randytarampi

Thanks so much for reaching out with this issue! I apologize for it and imagine it's frustrating. 😞 

I will fix it asap (tonight/tomorrow). I'm actively making this repository awesome! Please bear with me. 🙏 🙏
